name: ${name}
version: ${version}
main: ${main}
load: STARTUP
authors: [ cyberpwn, NextdoorPsycho, Vatuu ]
website: volmit.com
description: More than a Dimension!
libraries:
  - org.mapdb:mapdb:3.1.0
  - org.bytedeco:cuda-platform:12.3-8.9-1.5.10
  - org.bytedeco:javacpp:1.5.10
  - net.bytebuddy:byte-buddy:1.14.14
  - net.bytebuddy:byte-buddy-agent:1.12.8
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - com.github.ben-manes.caffeine:caffeine:3.0.5
  - org.apache.commons:commons-lang3:3.12.0
  - commons-io:commons-io:2.13.0
  - io.timeandspace:smoothie-map:2.0.2
  - com.google.guava:guava:31.0.1-jre
  - com.google.code.gson:gson:2.10.1
  - org.zeroturnaround:zt-zip:1.14
  - it.unimi.dsi:fastutil:8.5.6
  - org.ow2.asm:asm:9.2
  - rhino:js:1.7R2
  - bsf:bsf:2.4.0
  - org.lz4:lz4-java:1.8.0
  - io.netty:netty-all:4.1.112.Final
commands:
  iris:
    aliases: [ ir, irs ]
api-version: '${apiversion}'
hotload-dependencies: false